name: Track Added .ipynb Files

on:
  push:
    branches:
      - '**'

jobs:
  track-ipynb-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install gitpython loguru

    - name: Run script to track added .ipynb files
      run: python track_ipynb_files.py

    # Generated logs and datas, and commit and push in github
      - name: Commit Files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git diff-index --quiet HEAD || git commit -m "updated logs, and uploaded datas" --allow-empty

      # Pushing the changes
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

